await app.set_bot_commands([
        BotCommand("start", "🚀 Start the Bot"),
        BotCommand("batch", "🫠 Extract in Bulk"),
        BotCommand("login", "🔑 Get Into the Bot"),
        BotCommand("logout", "🚪 Get Out of the Bot"),
        BotCommand("token", "🎲 Get 3 Hours Free Access"),
        BotCommand("adl", "🎙️ Download Audio from 30+ Sites"),
        BotCommand("dl", "🎞️ Download Videos from 30+ Sites"),
        BotCommand("graph", "📇 Create Telegraph Posts"),
        BotCommand("freez", "🧊 Remove all Expired User"),
        BotCommand("pay", "💸 Pay now to get Subscription"),
        BotCommand("transfer", "💘 Gift Premium to Others"),
        BotCommand("myplan", "⌛ Get your Plan Details"),
        BotCommand("add", "➕ Add User to Premium"),
        BotCommand("rem", "➖ Remove from Premium"),
        BotCommand("settings", "⚙️ Personalize Settings"),
        BotCommand("stats", "📊 Get Stats of the Bot"),
        BotCommand("plan", "🗓️ Check Our Premium Plans"),
        BotCommand("terms", "🥺 Terms & Conditions"),
        BotCommand("speedtest", "🚅 Speed of Server"),
        BotCommand("lock", "🔒 Protect Channel from Extraction"),
        BotCommand("gcast", "⚡ Broadcast Message to Bot Users"),
        BotCommand("help", "❓ If you're a Noob, Still!"),
        BotCommand("cancel", "🚫 Cancel Batch Process")
    ])
